
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 18
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0


NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.NAT_FOCUS_YEARS = 15
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.MINIMUM_POLICY_TIME = 5

NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 40

NDefines.NGame.DAYS_BEHIND_PAUSE = 90 -- 25
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 30 -- 10
NDefines.NAI.AGGRESSIVENESS = 300 -- Vanilla 200
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 500 -- Vanilla 300
